# Generated by Django 2.0.1 on 2018-01-31 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OJUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=60, verbose_name='Username for identification')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineJudge',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='OnlineJudge Name')),
                ('url', models.URLField(verbose_name='OnlineJudge Website Index')),
            ],
        ),
        migrations.AddField(
            model_name='ojuser',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.OnlineJudge'),
        ),
        migrations.AddField(
            model_name='ojuser',
            name='realUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
